sudo: required
services:
  - docker

branches:
  except:
  - /^feature.*$/
  - /^bugfix.*$/
  - /^hotfix.*$/

language: go

go:
  - tip

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c7b1ce86dbe3d488dc79
    on_success: change
    on_failure: always
    on_start: never

install:
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s'
  - docker build -t "$DOCKER_USER"/go-ssl-redirect:$TRAVIS_TAG .
  - ./test.sh

deploy:
  skip_cleanup: true
  provider: script
  script: ./docker-deploy.sh
  on:
    tags: true
