sudo: required
services:
  - docker

branches:
  only:
  - master

language: go

go:
  - tip

notifications:
  email: false

install:
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s'
  - docker build -t "$DOCKER_USER"/go-ssl-redirect:latest .

deploy:
  skip_cleanup: true
  provider: script
  script: ./docker-deploy.sh
  on:
    branch: master
